projeto20/noteon4/urls.py
from django.urls import path
from . import views


app_name="noteon4"

urlpatterns=[
	#tTelas:
	path('',views.viewtindex,name="viewtindex"),
	

	
	path('tlogin/',views.viewtlogin,name="tlogin"),

	path('tregistro/',views.viewtregistro,name="tregistro"),
	
	path('tvernota/<int:id> <int:id2>',views.viewtvernota,name="tvernota"),

	path('tpainel/<int:id>',views.viewtpainel,name="tpainel"),
	
	path('tperfil/<int:id>',views.viewtperfil,name="tperfil"),
	

	#defbtn:
	path('defbtnregistro/',views.defbtnregistro,name='defbtnregistro'),

	path('defbtnlogin/',views.defbtnlogin,name="defbtnlogin"),
	
	path('defbtnnvnota/<int:id>',views.defbtnnvnota,name="defbtnnvnota"),

	path('defsavenvnota/<int:id>',views.defsavenvnota,name="defsavenvnota"),

	path('defeditar/<int:id> <int:id2>',views.defeditar,name="defeditar"),

	path('defeditarperfil/<int:id>',views.defeditarperfil,name="defeditarperfil"),
	
	path('defdeletar/<int:id> <int:id2>',views.defdeletar,name="defdeletar"),
]

projeto20/projeto20/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('noteon4.urls')),
]

projeto20/noteon4/models.py
from django.db import models

class usuarios(models.Model):
	nome=models.CharField(max_length=50)
	sobrenome=models.CharField(max_length=50)
	senha=models.CharField(max_length=50)
	email=models.EmailField()
	def __str__(self):
		return f'{self.nome},{self.sobrenome},{self.email},{self.senha}'

class anotacoes(models.Model):
	titulo=models.CharField(max_length=50)
	subtitulo=models.CharField(max_length=50)
	cor=models.CharField(max_length=50)
	texto=models.TextField()
	def __str__(self):
		return f'{self.titulo},{self.subtitulo},{self.cor},{self.texto}'


projeto20/noteon4/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.shortcuts import get_object_or_404 as error404
from  .models import usuarios, anotacoes 
from . import urls

def viewtindex(request):
	return render(request,'index.html')

def viewtlogin(request):
	return render(request,'tlogin.html')

def viewtregistro(request):
	return render(request,'tregistro.html')

def viewtpainel(request,id):
	try:
		usuario=error404(usuarios,pk=id)
		nota=anotacoes.objects.all()
		return render(request,'tpainel.html',{'USUARIO':usuario,'NOTA':nota})
	except:
		return HttpResponse("Ocorreu um Erro Fatal - Contate o Suporte (ERROR:003)")

def viewtvernota(request,id,id2):
	try:
		usuario=usuarios.objects.get(pk=id)	
		nota=anotacoes.objects.get(pk=id2)
		return render(request,'tvernota.html',{'USUARIO':usuario,'NOTA':nota})
	except:
		return HttpResponse("Ocorreu um Erro Fatal - Contate o Suporte (ERROR:005)")


def viewtperfil(request,id):
	try:
		usuario=usuarios.objects.get(pk=id)	
		return render(request,'tperfil.html',{'USUARIO':usuario})
	except:
		return HttpResponse("Ocorreu um Erro Fatal - Contate o Suporte (ERROR:007)")


def defbtnregistro(request):
	if request.method=="POST":
		email=request.POST.get('email')
		bdemails=usuarios.objects.filter(email=email)
		
		if not bdemails:
			nome=request.POST.get('nome')
			sobrenome=request.POST.get('sobrenome')
			email=request.POST.get('email')
			senha=request.POST.get('senha')
			nvusario=usuarios(nome=nome,sobrenome=sobrenome,senha=senha,email=email)
			nvusario.save()
			return render(request,'tlogin.html',{'kepEmail':email,'kepSenha':senha})
		else:
			nome=request.POST.get('nome')
			sobrenome=request.POST.get('sobrenome')
			email=request.POST.get('email')
			senha=request.POST.get('senha')
			return render(request,'tregistro.html',{'kepEmail':email,'kepSenha':senha,'EmailAlert':"Email já cadastrado",'kepNome':nome,'kepSobrenome':sobrenome})
	else:
		return HttpResponse("Ocorreu um Erro Fatal - Contate o Suporte (ERROR:001)")


def defbtnlogin(request):
	if request.method=="POST":
		email=request.POST.get('email')
		senha=request.POST.get('senha')
		try:
			bdemails=error404(usuarios,email=email)
		except:
			return render(request,'tlogin.html',{'EmailAlert':"Email Não Encontrado",'kepSenha':senha,'kepEmail':email})
		if bdemails.senha == senha:

			userId=usuarios.objects.get(email=email)
			nota=anotacoes.objects.all()
			return render(request,'tpainel.html',{'USUARIO':userId,'NOTA':nota})
		else:
			return render(request,'tlogin.html',{'SenhaAlert':"Senha Errada",'kepSenha':senha,'kepEmail':email})
	
	return HttpResponse("Ocorreu um Erro Fatal - Contate o Suporte (ERROR:002)")


def defbtnnvnota(request,id):
	usuario=usuarios.objects.get(pk=id)
	return render(request,'tnvnota.html',{'USUARIO':usuario})


def defsavenvnota(request,id):
	if request.method=="POST":
		titulo=request.POST.get('titulo')
		subtitulo=request.POST.get('subtitulo')
		cor=request.POST.get('cor')
		texto=request.POST.get('texto')
		nvnota=anotacoes(titulo=titulo,subtitulo=subtitulo,cor=cor,texto=texto)
		nvnota.save()
		usuario=usuarios.objects.get(pk=id)
		nota=anotacoes.objects.all()
		return render(request,'tpainel.html',{'USUARIO':usuario,'NOTA':nota})
	else: 
		return HttpResponse("Ocorreu um Erro Fatal - Contate o Suporte (ERROR:004)")

def defeditar(request,id,id2):
	if request.method=="POST":
			nota=anotacoes.objects.get(pk=id2)
			nota.subtitulo=request.POST.get('subtitulo')
			nota.texto=request.POST.get('texto')
			nota.cor=request.POST.get('cor')
			nota.titulo=request.POST.get('titulo')
			nota.save()
			
			usuario=usuarios.objects.get(pk=id)
			notas=anotacoes.objects.all()
			return render(request,'tpainel.html',{'USUARIO':usuario, 'NOTA':notas})
	else:
		return HttpResponse("Ocorreu um Erro Fatal - Contate o Suporte (ERROR:006)")


def defeditarperfil (request,id):
	if request.method=="POST":
		usuario=usuarios.objects.get(pk=id)
		usuario.nome=request.POST.get('nome')
		usuario.sobrenome=request.POST.get('sobrenome')
		usuario.email=request.POST.get('email')
		usuario.senha=request.POST.get('senha')
		usuario.save()

		return render(request,'tperfil.html',{'USUARIO':usuario})
	else:
		return HttpResponse("Ocorreu um Erro Fatal - Contate o Suporte (ERROR:006)")		

def defdeletar(request,id,id2):	
	try:	
		nota=anotacoes.objects.get(pk=id2)
		try:
			nota.delete()
		except:
			usuario=usuarios.objects.get(pk=id)	
			notas=anotacoes.objects.all()
			return render(request,'tpainel.html',{'USUARIO':usuario,'NOTA':notas})

		usuario=usuarios.objects.get(pk=id)	
		notas=anotacoes.objects.all()
		return render(request,'tpainel.html',{'USUARIO':usuario,'NOTA':notas})
	except:
		try:
			usuario=usuarios.objects.get(pk=id)	
			notas=anotacoes.objects.all()
			return render(request,'tpainel.html',{'USUARIO':usuario,'NOTA':notas})
		except:
			return HttpResponse("Ocorreu um Erro Fatal - Contate o Suporte (ERROR:009)")

projeto20/noteon4/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<title>NoteOn4</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
			  <a class="navbar-brand" href="">NoteOn4</a>
			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="navbar-toggler-icon"></span>
			  </button>
			  <div class="collapse navbar-collapse" id="navbarText">
			    <ul class="navbar-nav mr-auto">
			      <li class="nav-item active">
			        <a class="nav-link" href="#"> Home <span class="sr-only">(current)</span></a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="#">Sobre</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="#">Crescimento</a>
			      </li>
			    </ul>
			    <span class="navbar-text">
			    	Eai, Como vai ser? <a href="{% url 'noteon4:tregistro' %}"> <strong> Registro </strong> </a> <!-- levando para página de cadastro -->
			    	ou
			    	<a href="{% url 'noteon4:tlogin' %}"> <strong> Login </strong> </a> <!-- levando para página de cadastro -->
			    </span>
			  </div>
			</nav>

			<div class="jumbotron">
				<h2>
					Olá Mundo!
				</h2>
				<p>
					This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="#">Learn more</a>
				</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4">
			<h2>
				Anote!
			</h2>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>
				Customize!
			</h2>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>
				Salvo Online!
			</h2>
			<p>
				Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
			</p>
			<p>
				<a class="btn" href="#">View details »</a>
			</p>
		</div>
	</div>
</div>
</body>
</html>

projeto20/noteon4/templates/tconfirma.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>NoteOn4</title>
</head>
<body>
		
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<nav>
				<ol class="breadcrumb">
					<li class="breadcrumb-item">
						<a href="">{{USUARIO.nome}}</a>		
					</li>
					<li class="breadcrumb-item">
						<a href="{% url 'noteon4:tpainel' USUARIO.id%}">Anotações</a>		
					</li>
					<li class="breadcrumb-item">
						<a href="{% url 'noteon4:tlogin'%}">Sair</a>		
					</li>
				</ol>
			</nav>
		</div>
	</div>
</div>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-8">
			<div class="jumbotron">
				<h2>
					Hello, world!
				</h2>
				<p>
					This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="#">Learn more</a>
				</p>
			</div>
		</div>
		<div class="col-md-4">
			<form role="form" method="POST" action="{% url 'noteon4:defsavenvnota' USUARIO.id%}">
				{% csrf_token %}
				<div class="form-group">
					<label for="exampleInputEmail1">
						Titulo
					</label>
					<input type="text" class="form-control" id="exampleInputEmail1" placeholder="Titulo" name="titulo" />
				</div>

				<div class="form-group">
					<label for="exampleInputEmail1">
						Subtitulo
					</label>
					<input type="text" class="form-control" id="exampleInputEmail1" placeholder="Subtitulo" name="subtitulo" />
				</div>

				<div class="form-group">
					<label for="exampleInputPassword1">
						Anotação
					</label>
					<textarea autofocus class="form-control" type="text" id="exampleInputPassword1" placeholder="Anotação" name="texto"></textarea>
				</div>

				<div class="form-group">
					<label for="exampleInputPassword1">
						Cor de fundo
					</label>
					<input type="color" name="cor" class="form-control" id="exampleInputPassword1" value="" placeholder="Senha" name="senha" />
				</div>

				<button type="submit" class="btn btn-primary">
					Salvar
				</button>
			</form>
		</div>
	</div>
</div>



</body>
</html>

projeto20/noteon4/templates/tlogin.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>NoteOn4</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="">NoteOn4</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"> Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Sobre</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Crescimento</a>
      </li>
    </ul>
    <span class="navbar-text">
    	Já Ainda não tem conta? Faça o <a href="{% url 'noteon4:tregistro' %}"> <strong> Registro! </strong> </a> <!-- levando para página de cadastro -->
    </span>
  </div>
</nav>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="col-md-8">
					<div class="jumbotron">
						<h2>
							Olá Mundo!
						</h2>
						<p>
							Veja a mais nova versão do NoteOn4!
						</p>
						<p>
							<a class="btn btn-primary btn-large" href="#">Saiba Mais</a>
						</p>
					</div>
				</div>
				<div class="col-md-4">
					<h3 style="text-align: center;">Login</h3>
						<form method="POST" role="form" action="{% url 'noteon4:defbtnlogin'%}">
						{% csrf_token %}
						<div class="form-group">
							<label for="exampleInputEmail1">
								Email
							</label>
							<input type="email" class="form-control" value="{{kepEmail}}" id="exampleInputEmail1" name="email" />
						</div>
						<div class="form-group">
							<label for="exampleInputPassword1">
								Senha
							</label>
							<input type="password" class="form-control" id="exampleInputPassword1" name="senha" value="{{kepSenha}}" />
						</div>
						<button type="submit" class="btn btn-primary">
							Entrar
						</button>

						{{SenhaAlert}}
						{{EmailAlert}}

					</form>
				</div>
			</div>
		</div>
	</div>
</div>

</body>
</html>

projeto20/noteon4/templates/tnvnota.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>NoteOn4</title>
</head>
<body>
		
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<nav>
				<ol class="breadcrumb">
					<li class="breadcrumb-item">
						<a href="{% url 'noteon4:tperfil' USUARIO.id %}">{{USUARIO.nome}}</a>		
					</li>
					<li class="breadcrumb-item">
						<a href="{% url 'noteon4:tpainel' USUARIO.id%}">Anotações</a>		
					</li>
					<li class="breadcrumb-item">
						<a href="{% url 'noteon4:tlogin'%}">Sair</a>		
					</li>
				</ol>
			</nav>
		</div>
	</div>
</div>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-8">
			<div class="jumbotron">
				<h2>
					Hello, world!
				</h2>
				<p>
					This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="#">Learn more</a>
				</p>
			</div>
		</div>
		<div class="col-md-4">
			<form role="form" method="POST" action="{% url 'noteon4:defsavenvnota' USUARIO.id%}">	
				{% csrf_token %}
				<div class="form-group">
					<label for="exampleInputEmail1">
						Titulo
					</label>
					<input type="text" class="form-control" id="exampleInputEmail1" placeholder="Titulo" name="titulo" />
				</div>

				<div class="form-group">
					<label for="exampleInputEmail1">
						Subtitulo
					</label>
					<input type="text" class="form-control" id="exampleInputEmail1" placeholder="Subtitulo" name="subtitulo" />
				</div>

				<div class="form-group">
					<label for="exampleInputPassword1">
						Anotação
					</label>
					<textarea autofocus class="form-control" type="text" id="exampleInputPassword1" placeholder="Anotação" name="texto"></textarea>
				</div>

				<div class="form-group">
					<label for="exampleInputPassword1">
						Cor de fundo
					</label>
					<input type="color" name="cor" class="form-control" id="exampleInputPassword1" value="" placeholder="Senha" name="senha" />
				</div>

				<button type="submit" class="btn btn-primary">
					Salvar
				</button>
			</form>
		</div>
	</div>
</div>



</body>
</html>

projeto20/noteon4/templates/tpainel.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>NoteOn4</title>
</head>
<body>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<nav>
				<ol class="breadcrumb">
					<li class="breadcrumb-item">
						<a href="{% url 'noteon4:tperfil' USUARIO.id %}">{{USUARIO.nome}}</a>		
					</li>
					<li class="breadcrumb-item">
						<a href="{% url 'noteon4:defbtnnvnota' USUARIO.id%}">Nova Nota</a>		
					</li>
					<li class="breadcrumb-item">
						<a href="{% url 'noteon4:tlogin'%}">Sair</a>		
					</li>
				</ol>
			</nav>
		</div>
	</div>
</div>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="jumbotron">
				<h2>
					Olá Mundo!
				</h2>
				<p>
					Veja a mais nova versão do NoteOn4!
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="#">Learn more</a>
				</p>
			</div>
		</div>
	</div>
<div class="card-columns">
{%for notas in NOTA %}
	<div class="card border-dark mb-3" style="max-width: 18rem;background-color: {{notas.cor}}">
	  <div class="card-body text-dark">
	    <h5 class="card-title">Titulo: {{notas.titulo}}</h5>
	    <h5 class="card-title">Subtitulo: {{notas.subtitulo}}</h5>
	    <p class="card-text">{{notas.texto}}</p>
	    <hr>

	    <a href="{% url 'noteon4:tvernota' USUARIO.id notas.id%}">
			<button type="button" class="btn btn-outline-dark">Abrir</button>
		</a>
		<a href="{% url 'noteon4:defdeletar' USUARIO.id notas.id%}">
			<button type="button" class="btn btn-outline-dark">Deletar</button>
		</a>

		{{VerAlert}}


		</a>
	  </div>
	</div>
{% endfor %}
</div>
</body>
</html>


projeto20/noteon4/templates/tperfil.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>NoteOn4</title>
</head>
<body>
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<nav>
				<ol class="breadcrumb">
					<li class="breadcrumb-item">
						{{USUARIO.nome}}
					</li>
					<li class="breadcrumb-item">
						<a href="{% url 'noteon4:tpainel' USUARIO.id%}">Anotações</a>
					</li>
					<li class="breadcrumb-item">
						<a href="{% url 'noteon4:tlogin'%}">Sair</a>
					</li>
				</ol>
			</nav>
		</div>
	</div>
</div>
<!-- {{LivrariaAlert}} -->
<div class="container-fluid">
	<form method="POST" action="{% url 'noteon4:defeditarperfil' USUARIO.id%}">
	   {% csrf_token %}
	  <div class="form-row">
	    <div class="col">
      		<label for="inputName">Nome</label>
	      <input type="text" class="form-control" value="{{USUARIO.nome}}" name="nome">
	    </div>
	    <div class="col">
      		<label for="inputName">Sobrenome</label>
	      <input type="text" class="form-control"  value="{{USUARIO.sobrenome}}" name="sobrenome">
	    </div>
	  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Email</label>
      <input type="email" class="form-control" id="inputEmail4" value="{{USUARIO.email}}" name="email">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Senha</label>
      <input type="password" class="form-control" id="inputPassword4" value="{{USUARIO.senha}}" name="senha">
    </div>
		{{UserAlert}}
		<div class="container-fluid">
			<!-- Botão para redirecionar para editar perfil -->
		  <button type="submit" class="btn btn-primary">Editar Perfil</button>
		</div>
  </div>
</form>
</body>
</html>

projeto20/noteon4/templates/tvernota.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>NoteOn4</title>
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="">{{USUARIO.nome}}</a>   
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'noteon4:defbtnnvnota' USUARIO.id%}">Nova Nota</a>    
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'noteon4:tlogin'%}">Sair</a>    
          </li>
        </ol>
      </nav>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-8">
          <div class="jumbotron">
            <h2>
              Olá Mundo!
            </h2>
            <p>
              Com o tempo você percebe que as pessoas são como livros: umas te enganam pela capa e outras te surpreendem pelo conteúdo
            </p>
          </div>
        </div>
        <div class="col-md-4">
          <form role="form" method="POST" action="{% url 'noteon4:defeditar' USUARIO.id   NOTA.id %}">
            {% csrf_token %}
            <div class="form-group">   
              <label for="exampleInputPassword1">
                Titulo
              </label>
              <input type="text" name="titulo"  class="form-control" id="exampleInputPassword1" value="{{NOTA.titulo}}"/>
            </div>
            <div class="form-group">  
              <label for="exampleInputPassword1">
                Subtitulo
              </label>
              <input type="text" name="subtitulo" class="form-control" id="exampleInputPassword1" value="{{NOTA.subtitulo}}"/>
            </div>

            <div class="form-group">  
              <label for="exampleInputPassword1">
                Anotação
              </label>
              <input type="text" name="texto" class="form-control" id="exampleInputPassword1" value="{{NOTA.texto}}"/>
            </div>

            <div class="form-group">
              <label for="exampleInputPassword1">
                Cor
              </label>
              <input type="color"  name="cor" class="form-control" id="exampleInputPassword1" value="{{NOTA.cor}}"/>
            </div>
            <div class="form-group">
            <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Salvar">
          </form>  
        </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>